[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SCALPEL"
authors = [{name = "Franz AKE", email = "fake@idibel.cat"}]
dynamic = ["version", "description"]
